name: screengrab-snap
base: core18
summary: creating screenshots (unofficial)
description: |
  a crossplatform application for fast creating screenshots of your desktop. 
  This is the unofficial snap packaging.
  Upstream: https://github.com/lxqt/screengrab

grade: stable
confinement: strict
architectures:
#  - build-on: all
  - build-on: i386
  - build-on: amd64

plugs: # plugs for theming, font settings, cursor and to use gtk3 file chooser
  gtk-3-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes:gtk-3-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes:icon-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes:sounds-themes
  libqtxdg-snap:
    interface: content
    target: $SNAP/libqtxdg-snap
    default-provider: libqtxdg-snap

layout:
  /usr/share/screengrab/translations:
    bind: $SNAP/usr/share/screengrab/translations

adopt-info: screengrab-snap
parts:
  screengrab-snap:
    source: https://github.com/lxqt/screengrab.git
    source-type: git
    source-tag: "1.101"
    plugin: cmake
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_INSTALL_LIBDIR=lib
      - -DCMAKE_BUILD_TYPE=Snap
      - -DDEV_VERSION=Snap
      - -DSG_EXT_UPLOADS=OFF

    after: [desktop-qt5]
    build-snaps:
      - libqtxdg-snap
    build-packages:
        - g++
        - libkf5windowsystem-dev
        - qtbase5-dev
        - qttools5-dev
        - qttools5-dev-tools
        - libqt5svg5-dev
        - libqt5x11extras5-dev
        - libx11-dev
        - libx11-xcb-dev
        - libxcb1-dev
        - libxcb-xfixes0-dev
        - pkg-config
        - libglib2.0-dev
    stage-packages:
        - libgcc1
        - libkf5windowsystem5
        - libqt5core5a
        - libqt5dbus5
        - libqt5gui5
        - libqt5network5
        - libqt5widgets5
        - libqt5x11extras5
        - libstdc++6
        - libx11-xcb1
        - libxcb-xfixes0
        - libqt5xml5
        - qt5-gtk-platformtheme
        - qttranslations5-l10n
        - ttf-ubuntu-font-family
        - dmz-cursor-theme
        - light-themes
        - adwaita-icon-theme
    override-pull: |
      snapcraftctl pull
      snapcraftctl set-version `git describe --tags`
#
    override-stage: |
      snapcraftctl stage
      sed -e '/^Name/s/ScreenGrab/ScreenGrab-snap/i' -i usr/share/applications/screengrab.desktop
#
    organize:
      usr/share/qt5/translations/*.qm: usr/share/screengrab/translations/

  qt5-gtk-platform:
    plugin: nil
    stage-packages:
      - qt5-gtk-platformtheme

  desktop-qt5:
      source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
      source-subdir: qt
      plugin: make
      make-parameters: ["FLAVOR=qt5"]
      build-packages:
        - qtbase5-dev
        - dpkg-dev
      stage-packages:
        - libxkbcommon0
        - ttf-ubuntu-font-family
        - dmz-cursor-theme
        - light-themes
        - adwaita-icon-theme
        - gnome-themes-standard
        - shared-mime-info
        - libqt5gui5
        - libgdk-pixbuf2.0-0
        - libgtk2.0-0
        - libqt5svg5 # for loading icon themes which are svg
        - try: [appmenu-qt5] # not available on core18
        - locales-all


apps:
  screengrab-snap:
    adapter: full
    command: usr/bin/screengrab
    command-chain:
      - bin/desktop-launch
    plugs:
      - unity7
      - x11
      - opengl
      - gsettings
      - home
      - network
      - network-bind
      - removable-media
      - raw-usb
      - wayland
      - desktop-legacy
      - desktop
      - mount-observe
      - hostname-control
      - network-control
      - browser-support
    desktop: usr/share/applications/screengrab.desktop
    environment:
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/screengrab:$SNAP/libqtxdg-snap/lib:$SNAP/libqtxdg-snap/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      # Use GTK3 cursor theme, icon theme and open/save file dialogs.
      QT_QPA_PLATFORMTHEME: gtk3
