name: screengrab-snap
base: core18
summary: creating screenshots (unofficial)
description: |
  a crossplatform application for fast creating screenshots of your desktop. 
  This is the unofficial snap packaging.
  Upstream: https://github.com/lxqt/screengrab

grade: stable
confinement: strict

adopt-info: screengrab-snap
apps:
  screengrab-snap:
    adapter: full
    command: usr/bin/screengrab
    command-chain:
      - bin/desktop-launch
    plugs:
      - unity7
      - x11
      - opengl
      - gsettings
      - home
      - removable-media
      - raw-usb
      - wayland
      - desktop-legacy
      - desktop
      - mount-observe
      - hostname-control
      - browser-support
    desktop: usr/share/applications/screengrab.desktop

parts:
  screengrab-snap:
    source: https://github.com/lxqt/screengrab.git
    source-type: git
    source-commit: b31bc6c37a273e50c298b2082f775404bdfedc03
    plugin: cmake
    configflags:
      - -DCMAKE_INSTALL_PREFIX=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr
      - -DCMAKE_INSTALL_LIBDIR=lib
      - -DCMAKE_BUILD_TYPE=Snap
      - -DDEV_VERSION=Snap
      - -DSG_EXT_UPLOADS=OFF

    after: [desktop-qt5]
    override-pull: |
      snapcraftctl pull
      c1=`git log --oneline -n 1`
      cd $SNAPCRAFT_PROJECT_DIR
      c2=`git log --oneline -n 1`
      d=`date +%y%m%d`
      { t1=${c1#???}; c1=${c1%$t1}; }
      { t2=${c2#???}; c2=${c2%$t2}; }
      ver="$d.$SNAP_ARCH-$c1.$c2"
      echo "Set version: $ver"
      snapcraftctl set-version $ver

    build-snaps:
      - libqtxdg-snap/latest/edge
    build-packages:
      - g++
      - libkf5windowsystem-dev
      - qtbase5-dev
      - qttools5-dev
      - qttools5-dev-tools
      - libqt5svg5-dev
      - libqt5x11extras5-dev
      - libx11-dev
      - libx11-xcb-dev
      - libxcb1-dev
      - libxcb-xfixes0-dev
      - pkg-config
      - libglib2.0-dev

    override-stage: |
      snapcraftctl stage
      sed -e '/^Name/s/$/ - snap/' -i usr/share/applications/screengrab.desktop
      sed -e 's|Icon=screengrab|Icon=${SNAP}/usr/share/icons/hicolor/32x32/apps/screengrab.png|g' -i usr/share/applications/screengrab.desktop
#
    stage-snaps:
      - libqtxdg-snap/latest/edge
    stage-packages:
      - libgcc1
      - libkf5windowsystem5
      - libqt5core5a
      - libqt5dbus5
      - libqt5gui5
      - libqt5network5
      - libqt5widgets5
      - libqt5x11extras5
      - libstdc++6
      - libx11-xcb1
      - libxcb-xfixes0
      - libqt5xml5
      - qttranslations5-l10n
      - ttf-ubuntu-font-family
      - dmz-cursor-theme
      - light-themes
      - adwaita-icon-theme
      - fcitx-frontend-qt5
    organize:
      snap/$SNAPCRAFT_PROJECT_NAME/current/usr: usr
      usr/share/qt5/translations/*.qm: usr/share/screengrab/translations/

  desktop-qt5:
      source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
      source-subdir: qt
      plugin: make
      make-parameters: ["FLAVOR=qt5"]
      build-packages:
        - qtbase5-dev
        - dpkg-dev
      stage-packages:
        - libxkbcommon0
        - ttf-ubuntu-font-family
        - dmz-cursor-theme
        - light-themes
        - adwaita-icon-theme
        - gnome-themes-standard
        - shared-mime-info
        - libqt5gui5
        - libgdk-pixbuf2.0-0
        - libgtk2.0-0
        - libqt5svg5 # for loading icon themes which are svg
        - try: [appmenu-qt5] # not available on core18
        - locales-all
